# ================================
# General Purpose Makefile
# ================================

# Project directories
CORE_DIR    := core
SDL_DIR := $(CORE_DIR)/SDL
BAS_DIR := $(CORE_DIR)/BAS
# DLL directories
# not needed 

# Source codes directories
SDL_SRC    := $(SDL_DIR)/src
BAS_SRC    := $(BAS_DIR)/src

# Include directories
SDL_INC    := $(SDL_DIR)/include
BAS_INC    := $(BAS_DIR)/include
# Automate directory collection
INC_DIR := $(filter %_INC,$(.VARIABLES))
# Add "-I" into list of include directories
INC_FLAGS := $(foreach dir,$(INC_DIR),-I$($(dir)))

# Object directories
SDL_OBJ    := $(SDL_DIR)/obj
BAS_OBJ    := $(BAS_DIR)/obj
# Automate object directory collection
CORE_OBJ   := $(filter %_OBJ,$(.VARIABLES))
# Test directories
TEST_DIR    := tests
TEST_SRC    := $(TEST_DIR)/src
TEST_OBJ    := $(TEST_DIR)/obj

# Vender directories
# not needed for now

# Executable path
BIN_DIR     := exec

# Compiler settings
CXX         := g++
# no warnings (-Wall -Wextra)
CXXFLAGS    := -w -std=c++17 $(shell pkg-config --cflags sdl2 SDL2_image SDL2_mixer SDL2_ttf SDL2_net SDL2_gfx\
		lua zlib\
		) $(INC_FLAGS) 

# libavcodec libavformat libswscale libswresample libavutil #


CPPFLAGS    := -MMD -MP  # for dependency tracking

# Source codes
SDL_SRCS	:= $(wildcard $(SDL_SRC)/*.cpp)
BAS_SRCS	:= $(wildcard $(BAS_SRC)/*.cpp)

# Object files
SDL_OBJS   := $(patsubst $(SDL_SRC)/%.cpp,$(SDL_OBJ)/%.o,$(SDL_SRCS))
BAS_OBJS   := $(patsubst $(BAS_SRC)/%.cpp,$(BAS_OBJ)/%.o,$(BAS_SRCS))

# dependency files
SDL_DEPS   := $(SDL_OBJS:.o=.d)
BAS_DEPS   := $(BAS_OBJS:.o=.d)

# automatically collect all core dependency variables
CORE_DEPS := $(filter %_DEPS,$(.VARIABLES))

# Test files (each .cpp builds to a separate exe)
TEST_SRCS   := $(wildcard $(TEST_SRC)/*.cpp)
TEST_OBJS   := $(patsubst $(TEST_SRC)/%.cpp,$(TEST_OBJ)/%.o,$(TEST_SRCS))
TEST_DEPS   := $(TEST_OBJS:.o=.d)
TEST_BINS   := $(patsubst $(TEST_SRC)/%.cpp,$(BIN_DIR)/%,$(TEST_SRCS))

.SECONDARY: $(SDL_OBJS) $(BAS_OBJS) $(TEST_OBJS)
# Default target
.PHONY: all
all: $(BIN_DIR)/RadioButtonTest

OBJ_RadioButtonTest := $(filter-out $(BAS_OBJ)/base64.o $(BAS_OBJ)/Tilemap.o, $(BAS_OBJS))

# Default rule for building test binaries
$(BIN_DIR)/RadioButtonTest: $(TEST_OBJ)/RadioButtonTest.o $(SDL_OBJS) $(OBJ_RadioButtonTest) | $(BIN_DIR)
	@echo "Linking $@"
	$(CXX) $^ -o $@ $(LDFLAGS)

#$(BIN_DIR)/%: $(TEST_OBJ)/%.o $(SDL_OBJS) $(BAS_OBJS) | $(BIN_DIR)
#	@echo "Linking $@"
#	$(CXX) $^ -o $@ $(LDFLAGS)

# Build rules
# Default rule for building test binaries
#bin/test2: $(TEST_OBJ)/test2.o $(DEPS_test2) | $(BIN_DIR)
#	@echo "Linking $@"
#	$(CXX) $^ -o $@ $(LDFLAGS_test2)

# Rule for test objects
$(TEST_OBJ)/%.o: $(TEST_SRC)/%.cpp | $(TEST_OBJ)
	@echo "Compiling test $<"
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

# Rule for core objects
$(SDL_OBJ)/%.o: $(SDL_SRC)/%.cpp | $(SDL_OBJ)
	@echo "Compiling core/SDL $<"
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@

#Rule for core objects	
$(BAS_OBJ)/%.o: $(BAS_SRC)/%.cpp | $(BAS_OBJ)
	@echo "Compiling core/BAS $<"
	$(CXX) $(CXXFLAGS) $(CPPFLAGS) -c $< -o $@ 


# libavcodec libavformat libswresample libswscale libavutil\


LDFLAGS := $(shell pkg-config --libs sdl2 SDL2_gfx SDL2_ttf SDL2_image SDL2_net SDL2_mixer\
lua zlib)

# Cleaning
.PHONY: clean
clean:
	rm -rf $(SDL_OBJ) $(BAS_OBJ) $(TEST_OBJ) $(BIN_DIR)

# Include dependency files
-include $(CORE_DEPS) $(TEST_DEPS)
